name: gloversal-admin
services:
  admin:
    build: .
    container_name: gloversal-admin
    ports:
      - "8080:8080"
    volumes:
      - ..:/project
    env_file:
      - .env
    restart: unless-stopped
